// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: catalog.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCatalogItem = `-- name: CreateCatalogItem :one
INSERT INTO items (code, name, price, stock_quantity, image_url, created_at, updated_at)
    VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
    RETURNING id, code, name, price, stock_quantity, image_url, created_at, updated_at
`

type CreateCatalogItemParams struct {
	Code          string         `json:"code"`
	Name          string         `json:"name"`
	Price         pgtype.Numeric `json:"price"`
	StockQuantity int32          `json:"stock_quantity"`
	ImageUrl      *string        `json:"image_url"`
}

func (q *Queries) CreateCatalogItem(ctx context.Context, arg CreateCatalogItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, createCatalogItem,
		arg.Code,
		arg.Name,
		arg.Price,
		arg.StockQuantity,
		arg.ImageUrl,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Price,
		&i.StockQuantity,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllCatalogItems = `-- name: GetAllCatalogItems :many
SELECT id, code, name, price, stock_quantity, image_url, created_at, updated_at
    FROM items
    ORDER BY created_at DESC
`

func (q *Queries) GetAllCatalogItems(ctx context.Context) ([]Item, error) {
	rows, err := q.db.Query(ctx, getAllCatalogItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Price,
			&i.StockQuantity,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCatalogItemByID = `-- name: GetCatalogItemByID :one
SELECT id, code, name, price, stock_quantity, image_url, created_at, updated_at
    FROM items
    WHERE id = $1
`

func (q *Queries) GetCatalogItemByID(ctx context.Context, id pgtype.UUID) (Item, error) {
	row := q.db.QueryRow(ctx, getCatalogItemByID, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Price,
		&i.StockQuantity,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateItemQuantity = `-- name: UpdateItemQuantity :one
UPDATE items
    SET stock_quantity = $2, updated_at = NOW()
    WHERE id = $1
    RETURNING id, code, name, price, stock_quantity, image_url, created_at, updated_at
`

type UpdateItemQuantityParams struct {
	ID            pgtype.UUID `json:"id"`
	StockQuantity int32       `json:"stock_quantity"`
}

func (q *Queries) UpdateItemQuantity(ctx context.Context, arg UpdateItemQuantityParams) (Item, error) {
	row := q.db.QueryRow(ctx, updateItemQuantity, arg.ID, arg.StockQuantity)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Price,
		&i.StockQuantity,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
