// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCatalogItem(ctx context.Context, arg CreateCatalogItemParams) (Item, error)
	GetAllCatalogItems(ctx context.Context) ([]Item, error)
	GetCatalogItemByID(ctx context.Context, id pgtype.UUID) (Item, error)
	UpdateItemQuantity(ctx context.Context, arg UpdateItemQuantityParams) (Item, error)
}

var _ Querier = (*Queries)(nil)
