apiVersion: v1
kind: Secret
metadata:
  name: azure-storage-secret
  namespace: default
type: Opaque
stringData:
  # host.minikube.internal: special address: from Minikube pod -> localhost
  connection-string: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://host.minikube.internal:10000/devstoreaccount1;QueueEndpoint=http://host.minikube.internal:10001/devstoreaccount1;"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: "dbadmin"
  POSTGRES_PASSWORD: "local123"
  POSTGRES_DB: "orders"