// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (user_id, user_name, status, order_price)
    VALUES ($1, $2, $3, $4)
    RETURNING id, user_id, user_name, order_price, status, is_active, created_at, updated_at
`

type CreateOrderParams struct {
	UserID     pgtype.UUID    `json:"user_id"`
	UserName   string         `json:"user_name"`
	Status     OrderStatus    `json:"status"`
	OrderPrice pgtype.Numeric `json:"order_price"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.UserID,
		arg.UserName,
		arg.Status,
		arg.OrderPrice,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserName,
		&i.OrderPrice,
		&i.Status,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_item (order_id, item_id, quantity, price_at_order)
    VALUES ($1, $2, $3, $4)
    RETURNING id, order_id, item_id, quantity, price_at_order, created_at, updated_at
`

type CreateOrderItemParams struct {
	OrderID      pgtype.UUID    `json:"order_id"`
	ItemID       pgtype.UUID    `json:"item_id"`
	Quantity     int32          `json:"quantity"`
	PriceAtOrder pgtype.Numeric `json:"price_at_order"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.ItemID,
		arg.Quantity,
		arg.PriceAtOrder,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ItemID,
		&i.Quantity,
		&i.PriceAtOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrderById = `-- name: DeleteOrderById :exec
UPDATE orders  
SET is_active = FALSE, updated_at = NOW() 
WHERE id = $1
`

func (q *Queries) DeleteOrderById(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrderById, id)
	return err
}

const getAllOrders = `-- name: GetAllOrders :many
SELECT
    o.id,
    o.user_id,
    o.user_name,
    o.status,
    o.order_price,
    o.created_at,
    o.updated_at,
    oi.id as item_id,
    oi.item_id as item_product_id,
    oi.quantity,
    oi.price_at_order,
    i.code,
    i.name,
    i.image_url
FROM orders o
LEFT JOIN order_item oi ON o.id = oi.order_id
LEFT JOIN items i ON oi.item_id = i.id
WHERE o.is_active = TRUE
ORDER BY o.created_at DESC
`

type GetAllOrdersRow struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	UserName      string             `json:"user_name"`
	Status        OrderStatus        `json:"status"`
	OrderPrice    pgtype.Numeric     `json:"order_price"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	ItemID        pgtype.UUID        `json:"item_id"`
	ItemProductID pgtype.UUID        `json:"item_product_id"`
	Quantity      *int32             `json:"quantity"`
	PriceAtOrder  pgtype.Numeric     `json:"price_at_order"`
	Code          *string            `json:"code"`
	Name          *string            `json:"name"`
	ImageUrl      *string            `json:"image_url"`
}

func (q *Queries) GetAllOrders(ctx context.Context) ([]GetAllOrdersRow, error) {
	rows, err := q.db.Query(ctx, getAllOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllOrdersRow
	for rows.Next() {
		var i GetAllOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserName,
			&i.Status,
			&i.OrderPrice,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ItemID,
			&i.ItemProductID,
			&i.Quantity,
			&i.PriceAtOrder,
			&i.Code,
			&i.Name,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemByID = `-- name: GetItemByID :one
SELECT id, code, name, price, stock_quantity, image_url
FROM items
WHERE id = $1
`

type GetItemByIDRow struct {
	ID            pgtype.UUID    `json:"id"`
	Code          string         `json:"code"`
	Name          string         `json:"name"`
	Price         pgtype.Numeric `json:"price"`
	StockQuantity int32          `json:"stock_quantity"`
	ImageUrl      *string        `json:"image_url"`
}

func (q *Queries) GetItemByID(ctx context.Context, id pgtype.UUID) (GetItemByIDRow, error) {
	row := q.db.QueryRow(ctx, getItemByID, id)
	var i GetItemByIDRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Price,
		&i.StockQuantity,
		&i.ImageUrl,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :many
SELECT
    o.id,
    o.user_id,
    o.user_name,
    o.status,
    o.order_price,
    o.created_at,
    o.updated_at,
    oi.id as item_id,
    oi.item_id as item_product_id,
    oi.quantity,
    oi.price_at_order,
    i.code,
    i.name,
    i.image_url
FROM orders o
LEFT JOIN order_item oi ON o.id = oi.order_id
LEFT JOIN items i ON oi.item_id = i.id
WHERE o.id = $1
ORDER BY oi.created_at ASC
`

type GetOrderByIDRow struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	UserName      string             `json:"user_name"`
	Status        OrderStatus        `json:"status"`
	OrderPrice    pgtype.Numeric     `json:"order_price"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	ItemID        pgtype.UUID        `json:"item_id"`
	ItemProductID pgtype.UUID        `json:"item_product_id"`
	Quantity      *int32             `json:"quantity"`
	PriceAtOrder  pgtype.Numeric     `json:"price_at_order"`
	Code          *string            `json:"code"`
	Name          *string            `json:"name"`
	ImageUrl      *string            `json:"image_url"`
}

func (q *Queries) GetOrderByID(ctx context.Context, id pgtype.UUID) ([]GetOrderByIDRow, error) {
	rows, err := q.db.Query(ctx, getOrderByID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrderByIDRow
	for rows.Next() {
		var i GetOrderByIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserName,
			&i.Status,
			&i.OrderPrice,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ItemID,
			&i.ItemProductID,
			&i.Quantity,
			&i.PriceAtOrder,
			&i.Code,
			&i.Name,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItemStock = `-- name: UpdateItemStock :one
UPDATE items
SET stock_quantity = stock_quantity - $2, updated_at = NOW()
WHERE id = $1 AND stock_quantity >= $2
RETURNING id, code, name, price, stock_quantity, image_url, created_at, updated_at
`

type UpdateItemStockParams struct {
	ID            pgtype.UUID `json:"id"`
	StockQuantity int32       `json:"stock_quantity"`
}

func (q *Queries) UpdateItemStock(ctx context.Context, arg UpdateItemStockParams) (Item, error) {
	row := q.db.QueryRow(ctx, updateItemStock, arg.ID, arg.StockQuantity)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Price,
		&i.StockQuantity,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, user_name, order_price, status, is_active, created_at, updated_at
`

type UpdateOrderStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status OrderStatus `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserName,
		&i.OrderPrice,
		&i.Status,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
