// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	DeleteOrderById(ctx context.Context, id pgtype.UUID) error
	GetAllOrders(ctx context.Context) ([]GetAllOrdersRow, error)
	GetItemByID(ctx context.Context, id pgtype.UUID) (GetItemByIDRow, error)
	GetOrderByID(ctx context.Context, id pgtype.UUID) ([]GetOrderByIDRow, error)
	UpdateItemStock(ctx context.Context, arg UpdateItemStockParams) (Item, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
}

var _ Querier = (*Queries)(nil)
