# k8s/azure/secrets-provider.yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "9e8c09a0-7ae9-4c2f-9d26-027e30231a63"
    keyvaultName: "myapp-kv-inv2026"
    objects: |
      array:
        - |
          objectName: storage-connection-string
          objectType: secret
        - |
          objectName: storage-name
          objectType: secret
        - |
          objectName: postgres-password
          objectType: secret
        - |
          objectName: postgres-user
          objectType: secret
        - |
          objectName: postgres-db
          objectType: secret
        - |
          objectName: queue-name
          objectType: secret
        - |
          objectName: invoices-blob-name
          objectType: secret
        - |
          objectName: images-blob-name
          objectType: secret
    tenantId: "ada575f6-4e91-4d1d-aa89-9b2d9f5810e3"
  secretObjects:
  - secretName: azure-storage-secret
    type: Opaque
    data:
    - objectName: storage-connection-string
      key: connection-string
    - objectName: storage-name
      key: storage-name
    - objectName: queue-name
      key: QUEUE_NAME
    - objectName: invoices-blob-name
      key: INVOICES_BLOB_NAME
    - objectName: images-blob-name
      key: IMAGES_BLOB_NAME
  - secretName: postgres-secret
    type: Opaque
    data:
    - objectName: postgres-user
      key: POSTGRES_USER
    - objectName: postgres-password
      key: POSTGRES_PASSWORD
    - objectName: postgres-db
      key: POSTGRES_DB