apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      serviceAccountName: aks-workload-identity
      containers:
        - name: order-service
          image: myappacrinv2026.azurecr.io/order-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081

          envFrom:
          - configMapRef:
              name: app-config

          env:
          - name: BLOB_PUBLIC_HOST # for local testing
            value: "localhost:10000"
          - name: SERVICE_PORT
            value: "8081"
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD
          - name: AZURE_STORAGE_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: azure-storage-secret
                key: connection-string

          volumeMounts:
          - name: secrets-store
            mountPath: "/mnt/secrets-store"
            readOnly: true

      volumes:
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "azure-keyvault-secrets"