name: Build, Push to ACR, and Deploy to AKS and ACA

on:
  push:
    branches:
      - main
    paths:
      - 'catalog-service/**'
      - 'order-service/**'
      - 'invoice-worker/**'
      - 'k8s/**'
      - '.github/workflows/build-acr.yml'
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
  ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}

jobs:
  build-catalog-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.0'
          cache-dependency-path: catalog-service/go.sum
      
      - name: Install dependencies
        working-directory: ./catalog-service
        run: go mod download
      
      - name: Run tests
        working-directory: ./catalog-service
        run: go test  -v ./...
      
      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ env.ACR_USERNAME }}
          password: ${{ env.ACR_PASSWORD }}
        
      - name: Build and Push Docker image
        working-directory: ./catalog-service
        run: |
          IMAGE_NAME=${{ env.ACR_LOGIN_SERVER }}/catalog-service
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{ github.sha }} .
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}
  
  build-order-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.0'
          cache-dependency-path: order-service/go.sum
      
      - name: Install dependencies
        working-directory: ./order-service
        run: go mod download
      
      - name: Run tests
        working-directory: ./order-service
        run: go test -v ./... 
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ env.ACR_USERNAME }}
          password: ${{ env.ACR_PASSWORD }}
      
      - name: Build and Push Docker image
        working-directory: ./order-service
        run: |
          IMAGE_NAME=${{ env.ACR_LOGIN_SERVER }}/order-service
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{github.sha}} .
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{github.sha}}
  
  build-invoice-worker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.0'
          cache-dependency-path: invoice-worker/go.sum
      
      - name: Install dependencies
        working-directory: ./invoice-worker
        run: go mod download
      
      - name: Run tests
        working-directory: ./invoice-worker
        run: go test -v ./...
      
      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ env.ACR_USERNAME }}
          password: ${{ env.ACR_PASSWORD }}
        
      - name: Build and Push Docker Image
        working-directory: ./invoice-worker
        run: |
          IMAGE_NAME=${{ env.ACR_LOGIN_SERVER }}/invoice-worker
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{github.sha}} .
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{github.sha}}

  deploy-to-aks:
    needs: [build-catalog-service, build-order-service]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        run: |
          az login -u ${{ secrets.AZURE_USERNAME }} -p ${{ secrets.AZURE_PASSWORD }} --allow-no-subscriptions

      - name: Get AKS Credentials
        run: |
          az aks get-credentials \
            --resource-group myapp-orders-invoices \
            --name myapp-aks-order-invoice \
            --file kubeconfig
          echo "KUBECONFIG=$(pwd)/kubeconfig" >> $GITHUB_ENV

      - name: Deploy Azure Resources
        run: kubectl apply -f k8s/azure/

      - name: Ensure Ingress Controller exists
        run: |
          if ! kubectl get deployment -n ingress-nginx ingress-nginx-controller &> /dev/null; then
            echo "Installing Ingress Controller..."
            kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.11.1/deploy/static/provider/cloud/deploy.yaml
          else
            echo "Ingress Controller already exists"
          fi
      
      - name: Wait for Ingress Controller to be ready
        run: |
          kubectl rollout status deployment/ingress-nginx-controller \
            -n ingress-nginx \
            --timeout=180s

      - name: Deploy Postgres
        run: kubectl apply -f k8s/postgres/

      - name: Deploy Services
        run: |
          kubectl apply -f k8s/catalog-service/
          kubectl apply -f k8s/order-service/
          kubectl rollout restart deployment/catalog-service
          kubectl rollout restart deployment/order-service
      

      - name: Deploy Ingress
        run: kubectl apply -f k8s/ingress.yaml

      - name: Deployment Summary
        run: |
          echo "Deployment complete!"
          kubectl get pods -A
          kubectl get services
    
  deploy-invoice-worker:
    needs: build-invoice-worker
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        run: |
          az login -u ${{ secrets.AZURE_USERNAME }} -p ${{ secrets.AZURE_PASSWORD }} --allow-no-subscriptions

      - name: Deploy to ACA
        run: |
          az containerapp update \
            --name invoice-worker \
            --resource-group myapp-orders-invoices \
            --image ${{ env.ACR_LOGIN_SERVER }}/invoice-worker:latest